name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:

  SAST:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Analyze Code
        uses: github/codeql-action/analyze@v3


  SCA:
    runs-on: ubuntu-latest
    needs: SAST  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Install Snyk
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Scan
        run: snyk test --severity-threshold=high || true

        

  DAST:
    runs-on: ubuntu-latest
    needs: SCA
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
  
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
  
      - name: Install Dependencies
        run: npm install
  
      - name: Start Node App
        run: |
          node app.js &
          sleep 10
  
  
      - name: Run OWASP ZAP Scan
        run: |
          docker run --rm \
            -v $(pwd):/zap/wrk/:rw \
            -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t http://localhost:3000 \
            -r report.html \
            -w report.md \
            -J report.json
  
    
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: |
            report.html
            report.md
            report.json
          
