name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:

  sast:
    name: SAST - CodeQL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  sca:
    - name: SCA - Snyk
      uses: snyk/actions/node@master
      env:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: test --severity-threshold=high

  dast:
  name: DAST - OWASP ZAP
  runs-on: ubuntu-latest
  needs: sca
  steps:
    - name: Run ZAP Scan
      run: |
        docker run -t owasp/zap2docker-stable zap-baseline.py -t https://example.com
